// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdEjvx42yQo7UK6hL6IcEGBiB_OBOSFRQ',
    appId: '1:731572366823:web:fc3fb63e1acdc27e58a142',
    messagingSenderId: '731572366823',
    projectId: 'eventasuperadmin',
    authDomain: 'eventasuperadmin.firebaseapp.com',
    storageBucket: 'eventasuperadmin.firebasestorage.app',
    measurementId: 'G-1132L0JRY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxnBWtqdL4IyRURl9dutSztceaD_ROZu0',
    appId: '1:731572366823:android:966ef6eca7b5fb7558a142',
    messagingSenderId: '731572366823',
    projectId: 'eventasuperadmin',
    storageBucket: 'eventasuperadmin.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdEjvx42yQo7UK6hL6IcEGBiB_OBOSFRQ',
    appId: '1:731572366823:web:db2e4c2ccbd545b058a142',
    messagingSenderId: '731572366823',
    projectId: 'eventasuperadmin',
    authDomain: 'eventasuperadmin.firebaseapp.com',
    storageBucket: 'eventasuperadmin.firebasestorage.app',
    measurementId: 'G-YT7QEYT0KM',
  );

}